DECK_COUNT: int = 8
BLACKJACK_PAYOUT: float = 3.0 / 2.0
SURRENDER = "late"
HIT_ON_SOFT_17 = True
DOUBLE_AFTER_SPLIT = True
# RESPLIT_ACES = False
SPLIT_LIMIT = 0

DEFAULT_BET = 5.0
DEFAULT_INSURANCE = 0.0
